name: "gradle CI workflow macos"

on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month  


jobs:
  
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-gradle
  build-macos-job:
    name: "Set up JDK 1.8 on macos-latest 10.15.7"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64        
    - name: "Grant execute permission for gradlew & build"
      run: |
        cd app5 && chmod +x gradlew
        echo "#####################################################"
        echo "######################## BUILD ########################"
        echo "#####################################################"
        ./gradlew clean build    

