name: "log4j gradle CI workflow OS matrix"

on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month  


jobs:
  

# https://github.com/corretto/hotpatch-for-apache-log4j2
  build-gradle-os-matrix-log4j:
    name: "log4j RCE from CVE-2021-44228"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        distro: [microsoft]       
        jdk: [11]      
        # os: [ubuntu-latest, macos-latest]
        # distro: [microsoft,temurin,zulu,adopt-hotspot,adopt-openj9,liberica]       
        # jdk: [ 8,11,16,17]
        jdk-arch: [x64]
    steps:
      - uses: actions/checkout@v2
      - name: "Setup java"
        uses: actions/setup-java@v1
        with:
          distribution: ${{ matrix.distro}}  # See 'Supported distributions' for available options
          java-version: ${{ matrix.jdk }} 
          architecture: ${{ matrix.jdk-arch }}  #x86 # optional - defaults to x64
      - name: "Verify java version"
        run: java -version 
      - name: "Verify gradle version"
        run: gradle -v        
      - name: "Run Gradle build"
        run: |
          echo "#####################################################"
          echo "######################## BUILD ########################"
          echo "#####################################################"
          git clone https://github.com/corretto/hotpatch-for-apache-log4j2.git
          cd hotpatch-for-apache-log4j2
          # build on linux, mac and Windows subsystem for linux
          ./gradlew build
          find / -name Log4jHotPatch.jar

  # build-gradle-windows-log4j:
  #   name: "log4j RCE from CVE-2021-44228"
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [windows-latest]
  #       distro: [microsoft,temurin,zulu,adopt-hotspot,adopt-openj9,liberica]       
  #       jdk: [ 8,11,16,17]
  #       jdk-arch: [x64]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: "Setup java"
  #       uses: actions/setup-java@v1
  #       with:
  #         distribution: ${{ matrix.distro}}  # See 'Supported distributions' for available options
  #         java-version: ${{ matrix.jdk }
  #         architecture: ${{ matrix.jdk-arch }}  #x86 # optional - defaults to x64
  #     - name: "Verify java version"
  #       run: java -version 
  #     - name: "Verify gradle version"
  #       run: gradle -v        
  #     - name: "Run Gradle build"
  #       run: |
  #         echo "#####################################################"
  #         echo "######################## BUILD ########################"
  #         echo "#####################################################"
  #         git clone https://github.com/corretto/hotpatch-for-apache-log4j2.git
  #         # cd hotpatch-for-apache-log4j2
  #         cd $GITHUB_WORKSPACE
  #         # build on linux, mac and Windows subsystem for linux
  #         .\gradlew.bat build