name: "gradle CI workflow windows"

on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month  


jobs:
  
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-gradle
  build-windows-job:
    name: "Set up JDK 1.8 on windows-latest Microsoft Windows Server 2019 Datacenter"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: "Grant execute permission for gradlew"
      run: chmod +x gradlew
    - name: "Build with Gradle"
      run: ./gradlew build    
    - name: "Run the Gradle package task"
      run: ./gradlew -b ci.gradle package      
