name: "gradle CI workflow windows"

on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month  


jobs:
  
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-gradle
  build-windows-job:
    name: "Set up JDK 1.8 on windows-latest Microsoft Windows Server 2019 Datacenter"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: "Grant execute permission for gradlew & build"
      run: |
        # cd app5 && chmod +x gradlew
        cd app5
        echo "#####################################################"
        echo "######################## BUILD ########################"
        echo "#####################################################"
        ./gradlew clean build    

  build-matrix-windows-job:
    name: "java matrix"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        distro: [microsoft]  
        # distro: [microsoft,temurin,zulu,adopt-hotspot,adopt-openj9,liberica]       
        jdk: ['17']
        # jdk: ['8','11','16','17']
        jdk-arch: [x64]
    steps:
      - uses: actions/checkout@v2
      - name: "Setup java"
        uses: actions/setup-java@v1
        with:
          distribution: ${{ matrix.distro}}  # See 'Supported distributions' for available options
          java-version: ${{ matrix.jdk }} 
          architecture: ${{ matrix.jdk-arch }}  #x86 # optional - defaults to x64
      - name: "Verify java version"
        run: java -version 
      - name: "Verify gradle version"
        run: gradle -v