name: "log4j gradle CI workflow OS matrix"

on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month  


jobs:
  

# https://github.com/corretto/hotpatch-for-apache-log4j2
  build-gradle-os-matrix-log4j:
    name: "log4j RCE from CVE-2021-44228"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # java: [ 8,11.0.3, 12, 13 ]
    steps:
      - uses: actions/checkout@v2
      - name: "Setup java"
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      # - name: "Verify java version"
      #   run: java -version 
      - name: "Verify gradle version"
        run: gradle -v        
      - name: "Grant execute permission for gradlew & build"
        run: |
          echo "#####################################################"
          echo "######################## BUILD ########################"
          echo "#####################################################"
          git clone https://github.com/corretto/hotpatch-for-apache-log4j2.git
          cd hotpatch-for-apache-log4j2
          # build on linux, mac and Windows subsystem for linux
          ./gradlew build

  build-gradle-windows-log4j:
    name: "log4j RCE from CVE-2021-44228"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        # java: [ 8,11.0.3, 12, 13 ]
    steps:
      - uses: actions/checkout@v2
      - name: "Setup java"
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      # - name: "Verify java version"
      #   run: java -version 
      - name: "Verify gradle version"
        run: gradle -v        
      - name: "Grant execute permission for gradlew & build"
        run: |
          echo "#####################################################"
          echo "######################## BUILD ########################"
          echo "#####################################################"
          git clone https://github.com/corretto/hotpatch-for-apache-log4j2.git
          cd hotpatch-for-apache-log4j2
          # build on linux, mac and Windows subsystem for linux
          .\gradlew.bat build