name: "gradle CI workflow ubuntu"

on:
  push:
    # branches: [ $default-branch ]
    branches: [ dev ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-gradle  
  build-linux-job:
    name: "Specifying the JVM version and architecture on ubuntu-18.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: "Set up JDK 1.8"
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8
    - name: "Set up JDK 9.0.4 for x64"
      uses: actions/setup-java@v1
      with:
          java-version: '9.0.4'
          architecture: x64        
    # - name: Build with Maven
    #   run: mvn --batch-mode --update-snapshots verify
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml
    - name: "Grant execute permission for gradlew"
      run: chmod +x gradlew
    - name: "Build with Gradle"
      run: ./gradlew build    
    - name: "Run the Gradle package task"
      run: ./gradlew -b ci.gradle package

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-gradle
  build-linux-caching-job:
    name: "Caching dependencies on ubuntu-18.04"
    runs-on: ubuntu-latest #ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64  
    - name: "Cache Gradle packages"
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: "Grant execute permission for gradlew"
      run: chmod +x gradlew        
    - name: "Build with Gradle"
      run: ./gradlew build
    - name: "Run the Gradle package task"
      run: ./gradlew -b ci.gradle package        
