name: "java distro matrix ubuntu CI workflow"

on:
  push:
    branches: [ dev ]


jobs:      

  build-jdk-matrix-job:
    name: "matrix jdk distribution on ubuntu-latest"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        distribution: [microsoft]
        java-version: ['17']    
    steps:
    - uses: actions/checkout@v2
    # - uses: actions/setup-java@v2
    #   with:
    #     distribution: 'microsoft' # See 'Supported distributions' for available options
    #     java-version: '17'
    - name: "compile"    
      run: |
        javac Sum.java
        java -cp . Sum          